org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.debug=false

# https://parchmentmc.org/docs/getting-started
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.21-nightly-SNAPSHOT

# https://projects.neoforged.net/neoforged/neoforge
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.2)
neo_version=26.1.2.68-beta
neo_version_range=[26,)
loader_version_range=[4,)

mod_id=netmusic
mod_name=Net Music Mod
mod_license=MIT
mod_version=1.5.2-neoforge+mc26.1
mod_group_id=com.github.tartaricacid
mod_authors=TartaricAcid, IMG, \u90dd\u5357\u6751, \u7425\u73c0\u9178, \u5e15\u91d1\u4f0a, SQwatermark
mod_description=A music player mod

