modLoader = "javafml"
loaderVersion = "[46,)"
license = "MIT"

[[mods]]
modId = "netmusic"
version = "${mod_version}"
displayName = "Net Music Mod"
authors = "TartaricAcid, IMG, 郝南村, 琥珀酸, 帕金伊, SQwatermark"
description = "A music player mod"

[[dependencies.netmusic]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netmusic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.netmusic]]
modId = "touhou_little_maid"
mandatory = false
versionRange = "[1.5.0,)"
ordering = "AFTER"
side = "BOTH"
